"""Regenerate universal pip constraints and align isolated pre-commit hooks."""

import argparse
import re
import subprocess
import sys
import tempfile
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HEADER = (
    "# Generated by python .github/scripts/tooling-constraints.py; do not edit pins.\n"
    "# Sources: pyproject.toml [dev,release] and requirements/tooling.in.\n"
    "# Targets: Python 3.11-3.14, Linux and Windows (pyproject.toml [tool.uv]).\n"
    "# Build isolation remains separately constrained by requirements/build.txt.\n\n"
)
HOOKS = {
    "https://github.com/astral-sh/ruff-pre-commit": "ruff",
    "https://github.com/commitizen-tools/commitizen": "commitizen",
}


def align_hooks(config: str, constraints: str) -> str:
    for repository, package in HOOKS.items():
        versions = set(
            re.findall(rf"^{package}==([^;\s]+)", constraints, flags=re.MULTILINE)
        )
        if len(versions) != 1:
            raise ValueError(f"Expected one universal version for hook {package}")
        pattern = rf"(repo: {re.escape(repository)}\s+rev: )\S+"
        config, count = re.subn(pattern, rf"\g<1>v{versions.pop()}", config)
        if count != 1:
            raise ValueError(f"Expected one configured hook repository for {package}")
    return config


def generate(root: Path, *, check: bool, upgrades: list[str]) -> bool:
    bootstrap = (root / "requirements/generator.txt").read_text(encoding="utf-8")
    expected = re.search(r"^uv==([^\s]+)$", bootstrap, flags=re.MULTILINE)
    if expected is None or version("uv") != expected.group(1):
        raise ValueError(
            "Install the pinned requirements/generator.txt before generating"
        )

    target = root / "requirements/tooling.txt"
    hooks = root / ".pre-commit-config.yaml"
    original = target.read_text(encoding="utf-8")
    config = hooks.read_text(encoding="utf-8")
    # Seed uv's output preferences with the reviewed pins, without making them
    # hard constraints: the resolver can update a coupled dependency if needed.
    with tempfile.TemporaryDirectory() as directory:
        output = Path(directory) / "tooling.txt"
        output.write_text(original, encoding="utf-8")
        command = [
            sys.executable,
            "-m",
            "uv",
            "pip",
            "compile",
            "pyproject.toml",
            "requirements/tooling.in",
            "--extra",
            "dev",
            "--extra",
            "release",
            "--universal",
            "--python-version",
            "3.11",
            "--python",
            sys.executable,
            "--no-python-downloads",
            "--no-sources",
            "--no-header",
            "--no-annotate",
            "--output-file",
            str(output),
        ]
        for package in upgrades:
            command.extend(["--upgrade-package", package])
        subprocess.run(command, cwd=root, check=True, stdout=subprocess.DEVNULL)
        generated = HEADER + output.read_text(encoding="utf-8")
    aligned = align_hooks(config, generated)
    if check:
        return original == generated and config == aligned
    target.write_text(generated, encoding="utf-8", newline="\n")
    hooks.write_text(aligned, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Verify without changing files"
    )
    parser.add_argument(
        "--upgrade-package", action="append", default=[], metavar="PACKAGE"
    )
    args = parser.parse_args()
    if args.check and args.upgrade_package:
        parser.error("--check cannot be combined with --upgrade-package")
    try:
        current = generate(ROOT, check=args.check, upgrades=args.upgrade_package)
    except (
        PackageNotFoundError,
        ValueError,
        OSError,
        subprocess.CalledProcessError,
    ) as error:
        print(f"Constraints generation failed: {error}", file=sys.stderr)
        return 1
    if not current:
        print(
            "Constraints/hooks are stale; run python .github/scripts/tooling-constraints.py"
        )
        return 1
    print("Constraints and hook versions are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
